### ISSUE TITLE
https://nix.fuel.network/ doesn't work 

### ISSUE THREAD

**Issue by andreolf** [FuelLabs/fuel.nix#105]
the link in here https://github.com/FuelLabs/fuel.nix doesn't work

<img width="1058" alt="Screenshot 2023-10-01 at 13 19 08" src="https://github.com/FuelLabs/fuel.nix/assets/15174764/6247b5e3-3a91-45e5-a90d-dfebfa92eb69">

**Comment by kayagokalp** [comment]
Thanks for the report 👌

**Comment by kayagokalp** [comment]
It is now operational.
