### ISSUE TITLE
GitHub Actions user needs permission to push to `master` branch for automated `refresh-manifests` CI

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel.nix#22]
cc @adlerjohn, is it possible to allow the GitHub @actions-user special permissions to push to `master`?

This is how the nightly cron job workflow automates refreshing the set of manifests each night:

https://github.com/FuelLabs/fuel.nix/blob/e0224ed6272392fe95c43d97185d3083d6fc571b/.github/workflows/refresh-manifests.yml#L9-L52

It was previously working before transferring the repo, but it looks like the repo protections block the direct push:

```
Push to branch master
Pushing to https://github.com/FuelLabs/fuel.nix.git
POST git-receive-pack (1626 bytes)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/FuelLabs/fuel.nix.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/FuelLabs/fuel.nix.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

https://github.com/FuelLabs/fuel.nix/actions/runs/3109748765/jobs/5040255324

**Comment by adlerjohn** [comment]
It should be possible to make an exception for that user. I'll take a gander this weekend or so and we'll see if it works.

**Comment by mitchmindtree** [comment]
Just had a quick look, it looks like this might be possible under the last "Require a pull request before merging" option, "Allow specified actors to bypass required pull requests" - something like this:

![Screenshot from 2022-10-06 20-34-45](https://user-images.githubusercontent.com/4587373/194280051-7c5303ab-90f2-4143-9fff-e0a542fbcb0e.png)

**Comment by freesig** [comment]
Any updates on this. Trying to use forc from nix and it's falling behind the std lib so I can't compile a super basic application.

**Comment by mitchmindtree** [comment]
@freesig I've manually updated the manifests here in the meantime: #32. You can use this branch now with something like:

```console
nix shell github:fuellabs/fuel.nix/mitchmindtree/refresh-manifests#forc
```

though note this will build it from scratch as the cache won't be populated yet.

**Comment by adlerjohn** [comment]
Just tried and this doesn't work because @actions-user isn't part of the org.

**Comment by adlerjohn** [comment]
@mitchmindtree I've disabled PR requirements for `master` for this repo as a workaround. Let's see how that works for now.

**Comment by mitchmindtree** [comment]
Looks to be working nicely, cheers!
