### ISSUE TITLE
Re-enable requiring 1 approval, but without breaking the `refresh-manifests` action

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel.nix#75]
Just a reminder that a while back we turned off the requirement for 1 review approval in order to allow the nightly `refresh-manifests` to commit directly to master.

We should find some way to re-enable it while permitting the github actions user to continue to push directly to `master` if possible.

@sdankel mentioned she found this option which might be useful for enabling this:

![image](https://github.com/FuelLabs/fuel.nix/assets/4587373/325c94f7-93ff-4250-9b2e-6bd6f2899795)

**Comment by Voxelot** [comment]
Closing as the service user can bypass the PR process while others opening PRs still require approvals. However, the issue with the current CI actions that directly push to master is that they don't run any CI before merging. This also reduces the effectiveness of the merging criteria, as the required jobs list is unset.
