### ISSUE TITLE
Enable the `fuellabs.github.io/fuel.nix` and `nix.fuel.network` URLs for the book

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel.nix#77]
As of #61, we [publish the new book to gh-pages](https://github.com/FuelLabs/fuel.nix/actions/runs/5153146357/jobs/9280023395), though we still need to enable `nix.fuel.network`.

I'm not sure if the `fuellabs.github.io/fuel.nix` link should start working automatically at some point, but we might want to ensure this link works going forward too?

**Comment by kayagokalp** [comment]
Closing as this is fixed.
