### ISSUE TITLE
Quick start and the book links on the readme are broken.

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/fuel.nix#82]
Potentially as a result of #81 since that's the only change that has landed since they were working.

**Comment by kayagokalp** [comment]
Hey @JoshuaBatty, I haven't been able to use the doc from the domain before the linked PR. Also the issue for the domain name is still up: #77. And you can see that [the run](https://github.com/FuelLabs/fuel.nix/actions/runs/5326986553) is sucessfull.

**Comment by kayagokalp** [comment]
Closing this issue as this is duplicate of #77 and not related to the #81. Feel free to re-open if you think otherwise.
